name: Tag Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish LiveBot Socket
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: livebot
        image-tag: discord-slashcommands-${{ github.event.release.tag_name }}
        dockerfile: LiveBot.Discord.SlashCommands/Dockerfile

    - name: Build and Publish LiveBot Socket
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: livebot
        image-tag: discord-socket-${{ github.event.release.tag_name }}
        dockerfile: LiveBot.Discord.Socket/Dockerfile

    - name: Build and Publish LiveBot Tiwtch Watcher
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: livebot
        image-tag: watcher-twitch-${{ github.event.release.tag_name }}
        dockerfile: LiveBot.Watcher.Twitch/Dockerfile
