name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file LiveBot.API/Dockerfile --tag bsquidwrd/livebot:$(GITHUB_SHA)
    - name: Login to Docker
      run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKER_ACCESS_USERNAME }} --password-stdin
    - name: Push to Docker
      run: docker image push bsquidwrd/livebot:$(GITHUB_SHA)
