name: Latest Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish-discord-slashcommands-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for main branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish LiveBot Slash Commands
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: livebot
        image-tag: discord-slashcommands-latest
        dockerfile: LiveBot.Discord.SlashCommands/Dockerfile

  build-and-publish-watcher-twitch-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for main branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish LiveBot Twitch Watcher
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: livebot
        image-tag: watcher-twitch-latest
        dockerfile: LiveBot.Watcher.Twitch/Dockerfile
