name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and publish Docker Image to GitHub Packages Registry
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        # GitHub token to push Docker image to GitHub Packages
        github-token: ${{ github.token }}
        # Docker Image name
        image-name: livebot
        # Docker Image tag
        image-tag: ${{ github.sha }}
        # Extract git-tag from repository
        extract-git-tag: true
        # Dockerfile name
        dockerfile: LiveBot.API/Dockerfile
        # Path to build context
        build-context: .
        # Pull the image before buiding it
        pull-image: false
