name: Tag Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: livebot
        image-tag: ${{ github.event.release.tag_name }}
        dockerfile: LiveBot.API/Dockerfile
