name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub
      run: ${{ github.token }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file LiveBot.API/Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/livebot:${{ github.sha }}
    - name: Push Docker Image
      run: docker push docker.pkg.github.com/${{ github.repository }}/livebot:${{ github.sha }}
